---

spring:
  datasource:
    url: jdbc:mariadb://MARIADB_IP:MARIADB_PORT/MARIADB_DATABASE
    username: MARIADB_USERNAME
    password: MARIADB_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update

...
